name: Build Image

on:
  workflow_call:
    inputs:
      db:
        type: string
      ref:
        type: string
        default: ${{ github.ref }}
      repository:
        type: string
        default: ${{ github.repository }}
      tag:
        type: string
        default: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: manager/src/main/docker/Dockerfile.native-micro-builder
          tags: quay.io/gingersnap/cache-manager-${{ inputs.db }}:${{ inputs.tag }}
          outputs: type=docker,dest=/tmp/${{ inputs.db }}.tar
          build-args: |
            DB_VENDOR=${{ inputs.db }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.db }}
          path: /tmp/${{ inputs.db }}.tar
