name: Build Images

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
      repository:
        type: string
        default: ${{ github.repository }}
      tag:
        type: string
        default: latest
    outputs:
      image-names:
        description: The names of the created image files
        value: ${{ jobs.meta.outputs.names }}
      image-tag:
        description: The tag of the created image files
        value: ${{ jobs.meta.outputs.tag }}

jobs:
  images:
    strategy:
      matrix:
        target: [ mysql, mssql, oracle, postgres ]
    uses: ./.github/workflows/build-image.yaml
    with:
      db: ${{ matrix.target }}
      ref: ${{ inputs.ref }}
      repository: ${{ inputs.repository }}
      tag: ${{ inputs.tag }}

  meta:
    needs: [images]
    runs-on: ubuntu-latest

    outputs:
      names: ${{ steps.meta.outputs.names }}
      tag: ${{ steps.meta.outputs.tag }}

    steps:
      - id: meta
        run: |
          echo "names=mysql postgres mssql oracle" >> $GITHUB_OUTPUT
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
